version: "3.8"
services:
  api-example:
    build: ./api-example
    command: ["npm", "run", "develop"]
    restart: always
    environment:
      - DATABASE_NAME=stream-arch
      - SERVICE_NAME=API-EXAMPLE
    volumes:
      - ./api-example/api:/app/api
      - ./api-example/lib:/app/lib
      - ./api-example/config:/app/config
      - ./api-example/extensions:/app/extensions
    ports:
      - "1360:1337"
    container_name: api-example
    env_file:
      - ./.env

  api-iphone:
    build: ./api-iphone
    command: ["npm", "run", "develop"]
    restart: always
    environment:
      - DATABASE_NAME=iphone-db
      - SERVICE_NAME=API-IPHONE
    volumes:
      - ./api-iphone/api:/app/api
      - ./api-iphone/lib:/app/lib
      - ./api-iphone/config:/app/config
      - ./api-iphone/extensions:/app/extensions
    ports:
      - "1361:1337"
    container_name: api-iphone
    env_file:
      - ./.env


networks:
  default:
    name: local
